services:
  - docker

dist: trusty

jobs:
  include:
    - stage: "All"
      name: "Tests"
      install: docker pull holochain/app-spec-rust:develop
      script:
        - . docker/run-update && ls -la /holochain/holosqape/holochain-rust && docker/run-test
